markdown: redcarpet
name: BC IT Product and Service Design Guide
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: bcgov
  url: https://bcgov.org


# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here

navigation:
- text: About This Guide
  internal: true
- text: The Problem
  url: m1_theproblem/
  internal: true
- text: The Opportunity
  url: m1_theopportunity/
  internal: true
- text: The Solution
  url: m1_thesolution/
  internal: true
- text: The Maturity Model
  url: m1_maturitymodel/
  internal: true
- text: The Design Process Map
  url: m1_designprocessmap/
  internal: true
  children: 
  - text: Phase 1
    url: m1_designprocessmap/m1_phase1
    internal: true
  children: 
  - text: Phase 2
    url: m1_designprocessmap/m1_phase2
    internal: true
  children: 
  - text: Phase 3
    url: m1_designprocessmap/m1_phase3
    internal: true
  children: 
  - text: Phase 4
    url: m1_designprocessmap/m1_phase4
    internal: true
  
repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/bcgov

back_link:
  url: "https://github.com/bcgov"
  text: Read more BC Government Guides

google_analytics_ua: UA-48605964-19

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
